### ISSUE TITLE
Trip requests returns missing 'lineName' error 

### ISSUE THREAD

**Issue by felixpitterling** [derhuerst/bvg-rest#12] opened 2022-01-26 06:05 UTC
**Example**

request: https://v5.bvg.transport.rest/trips/1|34726|2|86|27012022&lineName=S1
response: {'error': True, 'msg': 'Missing lineName.', 'statusCode': 400}

How would I go about doing a trip request correctly? Thanks for any help.

**Comment by derhuerst** [comment] 2022-01-27 17:38
Note the `&` between the trip ID and the `lineName` parameter. It should be `?`, which in a URL separates the path from the query string.

**Comment by derhuerst** [comment] 2022-02-18 16:35
I'm going to close this Issue. Please re-open if the problem is not solved.

**Closed as completed by derhuerst** 2022-02-18 16:35 UTC
Labels: question
