### ISSUE TITLE
API Not Working Since Monday (05.08.2024)

### ISSUE THREAD

**Issue by ippen** [derhuerst/bvg-rest#23] opened 2024-08-07 20:51 UTC
#### Description:
Since Monday, the API has stopped working. This issue also affects the [API Playground](https://petstore.swagger.io/?url=https%3A%2F%2Fv6.bvg.transport.rest%2F.well-known%2Fservice-desc%0A), which is currently broken. Additionally, I attempted to use the provided Docker image but encountered an error when accessing the API on localhost.

#### Steps to Reproduce:
1. Run the provided Docker image using the following command:

   ```bash
   docker run -d -p 3000:3000 derhuerst/bvg-rest:6
   ```

2. Use the following curl command to access the API on localhost:

   ```bash
   curl 'localhost:3000/locations/nearby?latitude=52.52725&longitude=13.4123'
   ```

#### Observed Behavior:
The following error message is returned:

```json
{
   "message": "CLIENTVERSION: HCI Core: Invalid client version",
   "isHafasError": true,
   "code": null,
   "isCausedByServer": false,
   "hafasCode": "CLIENTVERSION",
   "url": "https://bvg-apps-ext.hafas.de/bin/mgate.exe?",
   "hafasResponseId": "dhhubzxk2xqah74k",
   "hafasMessage": "HCI Core: Invalid client version"
}
```

#### Appreciation and Engagement:
I greatly appreciate the work that goes into maintaining this project. It has been incredibly useful for my small widget using KWGT to show me the time of my bus, which relies on this API. You can see the project [here](https://github.com/ippen/kwgt?tab=readme-ov-file#ibc---bus-center).

I am also interested in supporting the project more and can sponsor via GitHub.

Thank you!

**Comment by matriphe** [comment] 2024-08-11 20:20
I suspected that BVG changed their API due to their new mobile app. I deployed https://github.com/public-transport/hafas-rest-api on my local and it returned a similar response:

Path: `/stops/{id}/departures`

```json
{
  "message": "CLIENTVERSION: HCI Core: Invalid client version",
  "isHafasError": true,
  "code": null,
  "isCausedByServer": false,
  "hafasCode": "CLIENTVERSION",
  "url": "https://bvg-apps-ext.hafas.de/bin/mgate.exe?",
  "hafasResponseId": "gwm84nccw8iugm4s",
  "hafasMessage": "HCI Core: Invalid client version"
}
```

Using the https://v6.bvg.transport.rest/ also returned 503.

**Comment by matriphe** [comment] 2024-08-11 20:22
I checked VBB endpoint from issue #22 and it returns the correct response!

**Comment by derhuerst** [comment] 2024-09-25 19:47
Thanks for reporting. I'm closing this Issue as a duplicate of #22.

**Closed as not planned by derhuerst** 2024-09-25 19:47 UTC
Labels: bug, duplicate
